name: Build and Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Setup system libraries
      run: sudo apt update && sudo apt install -y git build-essential

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get cached modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Run Gosec Security Scanner
      uses: securego/gosec
      with:
        args: ./...

    - name: Test
      run: make test