name: demo
on: push

env:
  REGISTRY_NAME: bradlab
  APP_NAME: myapplication

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@main

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.AZ_SP_CLIENT_ID }} 
        password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

    - name: Build the Docker image
      run: docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

    - name: Push Image to Docker
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
