name: demo
on: push

env:
  REGISTRY_NAME: bradlab
  APP_NAME: myapplication

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Build the Docker image
      run: docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.AZ_SP_CLIENT_ID }} 
        password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

    - name: Push Image to ACR
      run: docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

    - name: Scan image for vulnerabilities
      uses: Azure/container-scan@v0.1
      id: container-scan
      continue-on-error: true
      with:
        image-name: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        username: ${{ secrets.AZ_SP_CLIENT_ID }} 
        password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

    - name: Post scan results to ASC
      uses: Azure/publish-security-assessments@v0
      with: 
        artifact-type: containerImage
        scan-results-path: ${{ steps.container-scan.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}
