name: Release
on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: myapplication

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get Release Version
      id: version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Build the Docker image
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: |
        echo $VERSION
        make build-image VERSION=$VERSION

    - name: Login to Docker
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Tag the Docker Image with Release Version
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: make tag

    - name: Push Image to Docker
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: make push