name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get Build Version
      id: version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/heads/}

    - name: Build the Docker image
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: |
        echo $VERSION
        make build-image

    - name: Tag the Docker Image with Release Version
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: make tag

  test-security:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Setup system libraries
      run: sudo apt update && sudo apt install -y git build-essential

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get cached modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      run: make test